---
# Install and configure Mailpit.
- name: Ensure mailpit install directory exists.
  file:
    path: "{{ mailpit_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Download and install mailpit binary
  ansible.builtin.unarchive:
    src: "{{ mailpit_release_url }}"
    dest: "{{ mailpit_install_dir }}"
    remote_src: yes

- name: Copy mailpit systemd unit file into place
  template:
    src: mailpit.unit.j2
    dest: /etc/systemd/system/mailpit.service
    owner: root
    group: root
    mode: 0755

- name: Ensure mailpit is enabled and will start on boot
  service:
    name: mailpit
    state: started
    enabled: yes
